export interface FamilyApp {
  id: string;
  name: string;
  tagline: string;
  description: string;
  url: string;
  icon: string;
  gradient: string;
  glowClass: string;
  accentColor: string;
  status: 'live' | 'coming-soon';
}

// ============================================================
// ADD NEW FAMILY APPS HERE — just add an object to this array!
// ============================================================
export const FAMILY_APPS: FamilyApp[] = [
  {
    id: 'eurovision',
    name: 'Eurovision Ranker',
    tagline: 'Rate. Rank. Celebrate.',
    description: 'Rate all 35 Eurovision 2026 entries, watch music videos, track family rankings over time, and see who has the best taste in music.',
    url: 'https://eurovision-family.vercel.app',
    icon: '🎤',
    gradient: 'from-pink-500 via-purple-500 to-blue-500',
    glowClass: 'glow-pink',
    accentColor: '#E91E8C',
    status: 'live',
  },
  {
    id: 'cruise',
    name: 'Cruise Planner',
    tagline: 'Plan. Drag. Sail.',
    description: 'Plan our Enchanted Princess 7-night Mediterranean & Aegean cruise from Rome — choose excursions, pick restaurants, and coordinate with family.',
    url: '/cruise',
    icon: '🚢',
    gradient: 'from-cyan-500 via-blue-500 to-indigo-500',
    glowClass: 'glow-cyan',
    accentColor: '#06B6D4',
    status: 'live',
  },
  {
    id: 'italian',
    name: 'Learn Italian',
    tagline: 'Listen. Learn. Win $100.',
    description: '100 essential Italian vacation phrases with flash cards, audio pronunciation, and a $100 challenge quiz — get all 100 right in a row to win.',
    url: '/italian',
    icon: '🇮🇹',
    gradient: 'from-green-500 via-white to-red-500',
    glowClass: 'glow-green',
    accentColor: '#009246',
    status: 'live',
  },
  {
    id: 'german',
    name: 'Learn German',
    tagline: 'Watch. Read. Speak.',
    description: 'Learn German with curated YouTube videos, synced bilingual transcripts, and a personal vocabulary builder with flash cards.',
    url: '/german',
    icon: '🇩🇪',
    gradient: 'from-yellow-500 via-red-500 to-yellow-500',
    glowClass: 'glow-orange',
    accentColor: '#EAB308',
    status: 'live',
  },
  {
    id: 'recipes',
    name: 'Family Recipes',
    tagline: 'Cook. Share. Devour.',
    description: 'Our family cookbook — recipes passed down, discovered, and invented. Rate them, comment, and never forget the secret ingredients.',
    url: '/recipes',
    icon: '🍳',
    gradient: 'from-orange-500 via-red-500 to-pink-500',
    glowClass: 'glow-orange',
    accentColor: '#F97316',
    status: 'live',
  },
  // ---- COMING SOON ----
  {
    id: 'events',
    name: 'Events',
    tagline: 'Plan. Gather. Remember.',
    description: 'Family calendar for birthdays, holidays, reunions, and all the things we don\'t want to miss.',
    url: '/events',
    icon: '📅',
    gradient: 'from-violet-500 via-purple-500 to-fuchsia-500',
    glowClass: 'glow-purple',
    accentColor: '#8B5CF6',
    status: 'live',
  },
  {
    id: 'todos',
    name: 'To Do List',
    tagline: 'Track. Check. Done.',
    description: 'Shared family to-do lists — assign tasks, set due dates, and celebrate when everything gets checked off.',
    url: '/todos',
    icon: '✅',
    gradient: 'from-emerald-500 via-green-500 to-teal-500',
    glowClass: 'glow-green',
    accentColor: '#10B981',
    status: 'live',
  },
  {
    id: 'travel',
    name: 'Travel',
    tagline: 'Dream. Plan. Explore.',
    description: 'Plan family trips together — vote on destinations, build itineraries, and keep a journal of adventures.',
    url: '/travel',
    icon: '✈️',
    gradient: 'from-cyan-500 via-blue-500 to-indigo-500',
    glowClass: 'glow-cyan',
    accentColor: '#06B6D4',
    status: 'live',
  },
  {
    id: 'recommendations',
    name: 'Recommendations',
    tagline: 'Share. Discover. Enjoy.',
    description: 'Movies, books, restaurants, shows — share what you love and find out what the family is into.',
    url: '/recommendations',
    icon: '💡',
    gradient: 'from-amber-500 via-yellow-500 to-orange-500',
    glowClass: 'glow-orange',
    accentColor: '#F59E0B',
    status: 'live',
  },
  {
    id: 'photos',
    name: 'Photos',
    tagline: 'Capture. Share. Relive.',
    description: 'Family photo albums — upload from trips, holidays, and everyday moments. Tag, comment, and reminisce.',
    url: '/photos',
    icon: '📸',
    gradient: 'from-rose-500 via-pink-500 to-red-500',
    glowClass: 'glow-pink',
    accentColor: '#F43F5E',
    status: 'live',
  },
  {
    id: 'grades',
    name: 'Grades',
    tagline: 'Track. Learn. Succeed.',
    description: 'Live grades dashboard from Canvas — GPA, course grades, missing assignments, and upcoming due dates.',
    url: '/grades',
    icon: '📚',
    gradient: 'from-blue-500 via-indigo-500 to-purple-500',
    glowClass: 'glow-blue',
    accentColor: '#6366F1',
    status: 'live',
  },
  {
    id: 'tools',
    name: 'Custom Apps',
    tagline: 'Build. Automate. Create.',
    description: 'Custom tools and automations — YouTube to Podcast converter, and more coming soon.',
    url: '/tools',
    icon: '🛠️',
    gradient: 'from-purple-500 via-pink-500 to-purple-500',
    glowClass: 'glow-purple',
    accentColor: '#A855F7',
    status: 'live',
  },
  {
    id: 'wishlist',
    name: 'Wish List',
    tagline: 'Wish. Share. Surprise.',
    description: 'Birthday lists, holiday wishes, and dream items. Secretly claim gifts for each other.',
    url: '/wishlist',
    icon: '🎁',
    gradient: 'from-pink-500 via-rose-500 to-red-500',
    glowClass: 'glow-pink',
    accentColor: '#EC4899',
    status: 'live',
  },
];
